workflows:
    sample-workflow:
        name: Codemagic yaml Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
    ios-workflow:
    name: iOS Workflow 
    # ....
    environment:
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: com.example.codemagicYamlDemo





    